plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/chentao/Desktop/产品实习生boss/账号开放平台网站"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]